### ISSUE TITLE
Drulo tiene el ejercicio 3 de la unidad 3 hecho para el orto.

### ISSUE THREAD

**Issue by Saldrul** [Saldrul/CursoPython#2]
"""
_Escriba un programa que consulte al usuario por una oración y comente al usuario cuantas veces aparecen todas las bocales considerando minúsculas, mayúsculas y acentos._
"""

Codigo mal hecho:

from collections import Counter

pone_oracion = input("Pone una oración: ")
contador = Counter(pone_oracion)
print(contador)

**Comment by bbambozzi** [comment]
Arreglado.
