### ISSUE TITLE
Drul necesita resolver un problema

### ISSUE THREAD

**Issue by Saldrul** [Saldrul/CursoPython#4]
Carpeta: Ejercicios_3
file: ejercicio_3_8_mejorado.py

Tengo un problema en la función comprar que no puedo hacer que el iden que vendría a ser el identificador de las compras aumente su valor cada vez que la función es llamada.

Siempre que llamo a la función comprar cuando hago un .append(iden)
iden siempre muestra el mismo valor y no aumenta.

**Comment by IgnacioVitale** [comment]
Lo estas reseteando a 0 todo el tiempo. Lo seteas a 0 en la linea 28, despues le sumas 1 en la 29, y la proxima vez lo volves a setear en 0.

**Comment by IgnacioVitale** [comment]
deberia ser una variable global quizas, fuera de la funcion comprar, parte de la clase, ahi la pones en 0, y en la funcion comprar le vas sumando de a 1
